/*
	COLLECTION(LISTAS/VETORES): SÃO ESTRUTURAS UTILIZADAS PARA GERENCIAMENTO DE MÚLTIPLAS LINHAS DE DADOS
			* ASSOCIATIVE ARRAYS(IS TABLE OF): não podem ser armazenados em memória;
			* NESTED TABLE: podem ser armazenados em memória;
			* VARRAY
*/
-- ASSOCIATIVE ARRAYS
SET SERVEROUTPUT  ON
SET VERIFY OFF
DECLARE 
    TYPE NUMERO_TABLE_TYPE IS TABLE OF NUMBER(2)
    INDEX BY BINARY_INTEGER;
    NUMERO_TABLE NUMERO_TABLE_TYPE;
BEGIN
    -- ARMAZENA NÚMEROS DE 1 A 10 EM UM ASSOCIATIVE ARRAY
    FOR I IN 1..10
    LOOP
        NUMERO_TABLE(I) := I;
    END LOOP;
    -- PROGRAMA FAZ UMA SÉRIE DE COISAS...
    -- LÊ O ASSOCIATIVE ARRAY E IMPRIME OS NÚMEROS ARMAZENADOS
    FOR I IN 1..10
    LOOP
        DBMS_OUTPUT.PUT_LINE('ASSOCIATIVE ARRAY: INDICE = '|| TO_CHAR(I)||', VALOR = '||TO_CHAR(NUMERO_TABLE(I)));
    END LOOP;
END;